"""Add language_code to Video model

Revision ID: 04b324cdc465
Revises: 4d49b41bb870
Create Date: 2026-04-26 19:57:17.522826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b324cdc465'
down_revision = '4d49b41bb870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('language_code')

    # ### end Alembic commands ###
