"""add_note_timing_columns

Revision ID: 1164f30ee0a4
Revises: 3b23e935807a
Create Date: 2026-03-28 20:28:39.700233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1164f30ee0a4'
down_revision = '3b23e935807a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_appear_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('note_duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('note_duration')
        batch_op.drop_column('note_appear_before')

    # ### end Alembic commands ###
