"""drop subtitle_lines table

Revision ID: 1bd7d8f4ce74
Revises: 94137bf266a4
Create Date: 2026-03-28 15:51:09.545693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd7d8f4ce74'
down_revision = '94137bf266a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS subtitle_lines")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitle_lines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('line_index', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.FLOAT(), nullable=False),
    sa.Column('duration', sa.FLOAT(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['subtitle_tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subtitle_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitle_lines_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###
