"""Add streak_freezes to user

Revision ID: 1e99aea500f2
Revises: 04b324cdc465
Create Date: 2026-04-28 10:14:59.538378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e99aea500f2'
down_revision = '04b324cdc465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index('idx_sentence_review', ['next_review_at', 'user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_freezes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('streak_freezes')

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index('idx_sentence_review')

    # ### end Alembic commands ###
