"""add progress tracking fields to lessons

Revision ID: 2c4f6e8ae336
Revises: 28f20961bfce
Create Date: 2026-03-28 16:29:03.680992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4f6e8ae336'
down_revision = '28f20961bfce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_spent', sa.Integer(), nullable=True))
        # Handle rename or drop if last_opened_at existed and isn't used
        # Check if it fails, fallback to ignoring drop
        try:
            batch_op.drop_column('last_opened_at')
        except:
            pass

    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        # Give a name to the FK to satisfy SQLite batch requirements
        batch_op.create_foreign_key('fk_sub_tracks_uploader', 'users', ['uploader_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_opened_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('time_spent')
        batch_op.drop_column('is_completed')
        batch_op.drop_column('last_accessed')

    # ### end Alembic commands ###
