"""add streak fields to user

Revision ID: 3b23e935807a
Revises: a97a22896999
Create Date: 2026-03-28 19:48:01.619291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b23e935807a'
down_revision = 'a97a22896999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('longest_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_study_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_study_date')
        batch_op.drop_column('longest_streak')
        batch_op.drop_column('current_streak')

    # ### end Alembic commands ###
