"""Add lesson_word_statuses table

Revision ID: 44a123fa054c
Revises: 4708017a48d9
Create Date: 2026-05-05 23:52:31.942764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a123fa054c'
down_revision = '4708017a48d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_word_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_lesson_word_statuses_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson_word_statuses')),
    sa.UniqueConstraint('lesson_id', 'lemma', name='_lesson_lemma_status_uc')
    )
    with op.batch_alter_table('lesson_word_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_word_statuses_lemma'), ['lemma'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_word_statuses_lesson_id'), ['lesson_id'], unique=False)

    with op.batch_alter_table('video_glossaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('_dictionary_term_uc'), type_='unique')
        batch_op.drop_constraint(batch_op.f('_lesson_term_uc'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_video_glossaries_term'))
        batch_op.create_unique_constraint('_dictionary_front_uc', ['dictionary_id', 'front'])
        batch_op.create_unique_constraint('_lesson_front_uc', ['lesson_id', 'front'])
        batch_op.create_index(batch_op.f('ix_video_glossaries_front'), ['front'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_glossaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_glossaries_front'))
        batch_op.drop_constraint('_lesson_front_uc', type_='unique')
        batch_op.drop_constraint('_dictionary_front_uc', type_='unique')
        batch_op.create_index(batch_op.f('ix_video_glossaries_term'), ['front'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('_lesson_term_uc'), ['lesson_id', 'front'])
        batch_op.create_unique_constraint(batch_op.f('_dictionary_term_uc'), ['dictionary_id', 'front'])

    with op.batch_alter_table('lesson_word_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_word_statuses_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_word_statuses_lemma'))

    op.drop_table('lesson_word_statuses')
    # ### end Alembic commands ###
