"""Squashed initial migration

Revision ID: 4708017a48d9
Revises: 
Create Date: 2026-05-01 23:49:23.839942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4708017a48d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges'))
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_name'), ['name'], unique=True)

    op.create_table('grammar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('formation', sa.JSON(), nullable=True),
    sa.Column('meaning', sa.String(length=500), nullable=True),
    sa.Column('signal_words', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('nuance', sa.Text(), nullable=True),
    sa.Column('points_to_note', sa.JSON(), nullable=True),
    sa.Column('similar_patterns', sa.JSON(), nullable=True),
    sa.Column('jlpt_level', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grammar'))
    )
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammar_is_exported'), ['is_exported'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_pattern'), ['pattern'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('central_auth_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('preferences_json', sa.Text(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_study_date', sa.Date(), nullable=True),
    sa.Column('total_exp', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('streak_freezes', sa.Integer(), nullable=True),
    sa.Column('total_listening_seconds', sa.Integer(), nullable=True),
    sa.Column('total_shadowing_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_central_auth_id'), ['central_auth_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('reading', sa.String(length=255), nullable=True),
    sa.Column('meaning', sa.String(length=500), nullable=True),
    sa.Column('kanji_breakdown', sa.Text(), nullable=True),
    sa.Column('mnemonic', sa.Text(), nullable=True),
    sa.Column('collocations', sa.JSON(), nullable=True),
    sa.Column('jlpt_level', sa.String(length=10), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary'))
    )
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_is_exported'), ['is_exported'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_word'), ['word'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_playlists_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_table('sentence_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('set_type', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sentence_sets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentence_sets'))
    )
    with op.batch_alter_table('sentence_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentence_sets_is_exported'), ['is_exported'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentence_sets_user_id'), ['user_id'], unique=False)

    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metric_value', sa.Integer(), nullable=True),
    sa.Column('exp_earned', sa.Integer(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activity_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activity_logs'))
    )
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_logs_user_id'), ['user_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('fk_user_badges_badge_id_badges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_badges_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_badges'))
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('curated_overview', sa.Text(), nullable=True),
    sa.Column('curated_grammar', sa.Text(), nullable=True),
    sa.Column('curated_vocabulary', sa.Text(), nullable=True),
    sa.Column('curated_sections', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_videos_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_youtube_id'), ['youtube_id'], unique=False)

    op.create_table('ai_insight_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_lines', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_ai_insight_tracks_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insight_tracks'))
    )
    with op.batch_alter_table('ai_insight_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insight_tracks_video_id'), ['video_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('video_timestamp', sa.Float(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_comments_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_video_id'), ['video_id'], unique=False)

    op.create_table('playlist_items',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_items_playlist_id_playlists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_playlist_items_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'video_id', name=op.f('pk_playlist_items'))
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('source_video_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('detailed_analysis', sa.JSON(), nullable=True),
    sa.Column('analysis_note', sa.Text(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sentence_sets.id'], name=op.f('fk_sentences_set_id_sentence_sets')),
    sa.ForeignKeyConstraint(['source_video_id'], ['videos.id'], name=op.f('fk_sentences_source_video_id_videos')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sentences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentences'))
    )
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.create_index('idx_sentence_review', ['next_review_at', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_is_exported'), ['is_exported'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_next_review_at'), ['next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_set_id'), ['set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_source_video_id'), ['source_video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentences_user_id'), ['user_id'], unique=False)

    op.create_table('share_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_share_requests_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_share_requests_sender_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_share_requests_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_requests'))
    )
    with op.batch_alter_table('share_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_requests_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_requests_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_requests_video_id'), ['video_id'], unique=False)

    op.create_table('subtitle_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('uploader_name', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_subtitle_tracks_uploader_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_subtitle_tracks_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtitle_tracks'))
    )
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subtitle_tracks_video_id'), ['video_id'], unique=False)

    op.create_table('video_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_video_collaborators_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_collaborators_video_id_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_collaborators')),
    sa.UniqueConstraint('video_id', 'user_id', name='_video_user_collaborator_uc')
    )
    op.create_table('ai_insight_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('subtitle_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('short_explanation', sa.String(length=500), nullable=True),
    sa.Column('grammar_analysis', sa.Text(), nullable=True),
    sa.Column('nuance_style', sa.Text(), nullable=True),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['ai_insight_tracks.id'], name=op.f('fk_ai_insight_items_track_id_ai_insight_tracks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_insight_items'))
    )
    with op.batch_alter_table('ai_insight_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insight_items_track_id'), ['track_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('original_lang_code', sa.String(length=10), nullable=True),
    sa.Column('target_lang_code', sa.String(length=10), nullable=True),
    sa.Column('third_lang_code', sa.String(length=10), nullable=True),
    sa.Column('s1_track_id', sa.Integer(), nullable=True),
    sa.Column('s2_track_id', sa.Integer(), nullable=True),
    sa.Column('s3_track_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('note_appear_before', sa.Float(), nullable=True),
    sa.Column('note_duration', sa.Float(), nullable=True),
    sa.Column('shadowing_extra_time', sa.Float(), nullable=True),
    sa.Column('shadowing_hide_subs', sa.Boolean(), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['s1_track_id'], ['subtitle_tracks.id'], name=op.f('fk_lessons_s1_track_id_subtitle_tracks')),
    sa.ForeignKeyConstraint(['s2_track_id'], ['subtitle_tracks.id'], name=op.f('fk_lessons_s2_track_id_subtitle_tracks')),
    sa.ForeignKeyConstraint(['s3_track_id'], ['subtitle_tracks.id'], name=op.f('fk_lessons_s3_track_id_subtitle_tracks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lessons_user_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_lessons_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons')),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_video_id'), ['video_id'], unique=False)

    op.create_table('sentence_grammar_association',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('grammar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_id'], ['grammar.id'], name=op.f('fk_sentence_grammar_association_grammar_id_grammar')),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_sentence_grammar_association_sentence_id_sentences')),
    sa.PrimaryKeyConstraint('sentence_id', 'grammar_id', name=op.f('pk_sentence_grammar_association'))
    )
    op.create_table('sentence_vocab_association',
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_sentence_vocab_association_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], name=op.f('fk_sentence_vocab_association_vocabulary_id_vocabulary')),
    sa.PrimaryKeyConstraint('sentence_id', 'vocabulary_id', name=op.f('pk_sentence_vocab_association'))
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_notes_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_is_exported'), ['is_exported'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)

    op.create_table('sentence_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('lemma_override', sa.String(length=255), nullable=True),
    sa.Column('pos', sa.String(length=50), nullable=True),
    sa.Column('reading', sa.String(length=255), nullable=True),
    sa.Column('meaning', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_sentence_tokens_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentence_tokens')),
    sa.UniqueConstraint('lesson_id', 'line_index', 'order_index', name='_lesson_line_order_uc')
    )
    op.create_table('shadowing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('accuracy_score', sa.Integer(), nullable=False),
    sa.Column('spoken_text', sa.Text(), nullable=True),
    sa.Column('user_audio_url', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('ai_feedback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_shadowing_history_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_shadowing_history_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shadowing_history_user_id_users')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_shadowing_history_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shadowing_history'))
    )
    with op.batch_alter_table('shadowing_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shadowing_history_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadowing_history_sentence_id'), ['sentence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadowing_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadowing_history_video_id'), ['video_id'], unique=False)

    op.create_table('video_dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('target_language_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_video_dictionaries_lesson_id_lessons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_dictionaries'))
    )
    op.create_table('video_glossaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('reading', sa.String(length=255), nullable=True),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('last_updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('target_language_code', sa.String(length=10), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['video_dictionaries.id'], name=op.f('fk_video_glossaries_dictionary_id_video_dictionaries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_video_glossaries_last_updated_by_users')),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_video_glossaries_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name=op.f('fk_video_glossaries_video_id_videos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_glossaries')),
    sa.UniqueConstraint('dictionary_id', 'term', name='_dictionary_term_uc'),
    sa.UniqueConstraint('lesson_id', 'term', name='_lesson_term_uc')
    )
    with op.batch_alter_table('video_glossaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_glossaries_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_glossaries_term'), ['term'], unique=False)

    op.create_table('vocab_edit_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glossary_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_definition', sa.Text(), nullable=True),
    sa.Column('new_definition', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['glossary_id'], ['video_glossaries.id'], name=op.f('fk_vocab_edit_histories_glossary_id_video_glossaries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocab_edit_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_edit_histories'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_edit_histories')
    with op.batch_alter_table('video_glossaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_glossaries_term'))
        batch_op.drop_index(batch_op.f('ix_video_glossaries_lesson_id'))

    op.drop_table('video_glossaries')
    op.drop_table('video_dictionaries')
    with op.batch_alter_table('shadowing_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shadowing_history_video_id'))
        batch_op.drop_index(batch_op.f('ix_shadowing_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_shadowing_history_sentence_id'))
        batch_op.drop_index(batch_op.f('ix_shadowing_history_lesson_id'))

    op.drop_table('shadowing_history')
    op.drop_table('sentence_tokens')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_notes_is_exported'))

    op.drop_table('notes')
    op.drop_table('sentence_vocab_association')
    op.drop_table('sentence_grammar_association')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_video_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_user_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('ai_insight_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insight_items_track_id'))

    op.drop_table('ai_insight_items')
    op.drop_table('video_collaborators')
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subtitle_tracks_video_id'))

    op.drop_table('subtitle_tracks')
    with op.batch_alter_table('share_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_requests_video_id'))
        batch_op.drop_index(batch_op.f('ix_share_requests_sender_id'))
        batch_op.drop_index(batch_op.f('ix_share_requests_receiver_id'))

    op.drop_table('share_requests')
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_user_id'))
        batch_op.drop_index(batch_op.f('ix_sentences_source_video_id'))
        batch_op.drop_index(batch_op.f('ix_sentences_set_id'))
        batch_op.drop_index(batch_op.f('ix_sentences_next_review_at'))
        batch_op.drop_index(batch_op.f('ix_sentences_is_exported'))
        batch_op.drop_index('idx_sentence_review')

    op.drop_table('sentences')
    op.drop_table('playlist_items')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_video_id'))
        batch_op.drop_index(batch_op.f('ix_comments_user_id'))

    op.drop_table('comments')
    with op.batch_alter_table('ai_insight_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insight_tracks_video_id'))

    op.drop_table('ai_insight_tracks')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_youtube_id'))

    op.drop_table('videos')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('user_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_logs_user_id'))

    op.drop_table('user_activity_logs')
    with op.batch_alter_table('sentence_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentence_sets_user_id'))
        batch_op.drop_index(batch_op.f('ix_sentence_sets_is_exported'))

    op.drop_table('sentence_sets')
    op.drop_table('playlists')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_word'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_is_exported'))

    op.drop_table('vocabulary')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_central_auth_id'))

    op.drop_table('users')
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_pattern'))
        batch_op.drop_index(batch_op.f('ix_grammar_is_exported'))

    op.drop_table('grammar')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_name'))

    op.drop_table('badges')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
