"""Add Community, Gamification and AI Standby

Revision ID: 4d49b41bb870
Revises: f72a6393b6f0
Create Date: 2026-04-16 21:23:49.607994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d49b41bb870'
down_revision = 'f72a6393b6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_edit_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glossary_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_definition', sa.Text(), nullable=True),
    sa.Column('new_definition', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['glossary_id'], ['video_glossaries.id'], name=op.f('fk_vocab_edit_histories_glossary_id_video_glossaries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vocab_edit_histories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_edit_histories'))
    )
    op.drop_table('ai_insight_items')
    op.drop_table('ai_insight_tracks')
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exported_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_grammar_is_exported'), ['is_exported'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exported_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_is_exported'), ['is_exported'], unique=False)

    with op.batch_alter_table('sentence_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exported_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sentence_sets_is_exported'), ['is_exported'], unique=False)

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exported_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sentences_is_exported'), ['is_exported'], unique=False)

    with op.batch_alter_table('shadowing_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_audio_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_feedback', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_exp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_listening_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_shadowing_count', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_central_auth_id'))
        batch_op.create_index(batch_op.f('ix_users_central_auth_id'), ['central_auth_id'], unique=True)

    with op.batch_alter_table('video_glossaries', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('term',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('reading',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'jamdict'"))
        batch_op.create_unique_constraint('_lesson_term_uc', ['lesson_id', 'term'])
        batch_op.create_index(batch_op.f('ix_video_glossaries_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_video_glossaries_term'), ['term'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_video_glossaries_lesson_id_lessons'), 'lessons', ['lesson_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_video_glossaries_last_updated_by_users'), 'users', ['last_updated_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_video_glossaries_video_id_videos'), 'videos', ['video_id'], ['id'])

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_exported', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('exported_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vocabulary_is_exported'), ['is_exported'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_is_exported'))
        batch_op.drop_column('exported_at')
        batch_op.drop_column('is_exported')

    with op.batch_alter_table('video_glossaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_video_glossaries_video_id_videos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_video_glossaries_last_updated_by_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_video_glossaries_lesson_id_lessons'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_video_glossaries_term'))
        batch_op.drop_index(batch_op.f('ix_video_glossaries_lesson_id'))
        batch_op.drop_constraint('_lesson_term_uc', type_='unique')
        batch_op.alter_column('source',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'jamdict'"))
        batch_op.alter_column('reading',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('term',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_central_auth_id'))
        batch_op.create_index(batch_op.f('ix_users_central_auth_id'), ['central_auth_id'], unique=False)
        batch_op.drop_column('total_shadowing_count')
        batch_op.drop_column('total_listening_minutes')
        batch_op.drop_column('current_level')
        batch_op.drop_column('total_exp')

    with op.batch_alter_table('shadowing_history', schema=None) as batch_op:
        batch_op.drop_column('ai_feedback')
        batch_op.drop_column('ai_score')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('user_audio_url')

    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentences_is_exported'))
        batch_op.drop_column('exported_at')
        batch_op.drop_column('is_exported')

    with op.batch_alter_table('sentence_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentence_sets_is_exported'))
        batch_op.drop_column('exported_at')
        batch_op.drop_column('is_exported')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_is_exported'))
        batch_op.drop_column('exported_at')
        batch_op.drop_column('is_exported')

    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_is_exported'))
        batch_op.drop_column('exported_at')
        batch_op.drop_column('is_exported')

    op.create_table('ai_insight_tracks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), server_default=sa.text("'vi'"), nullable=False),
    sa.Column('engine', sa.VARCHAR(length=50), server_default=sa.text("'gemini'"), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_lines', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('total_lines', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('overall_summary', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_insight_items',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('subtitle_index', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.FLOAT(), nullable=False),
    sa.Column('end_time', sa.FLOAT(), nullable=False),
    sa.Column('short_explanation', sa.VARCHAR(length=500), nullable=True),
    sa.Column('grammar_analysis', sa.TEXT(), nullable=True),
    sa.Column('nuance_style', sa.TEXT(), nullable=True),
    sa.Column('context_notes', sa.TEXT(), nullable=True),
    sa.Column('data_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['ai_insight_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vocab_edit_histories')
    # ### end Alembic commands ###
