"""Added third_lang_code to Lesson

Revision ID: 67fa9ad740ba
Revises: afda5c4560cf
Create Date: 2026-03-28 14:37:16.215733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fa9ad740ba'
down_revision = 'afda5c4560cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('third_lang_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('third_lang_code')
    # ### end Alembic commands ###
