"""AuraFlow Redesign: Add sentence track and update shadowing history

Revision ID: 723a96a8f359
Revises: 1164f30ee0a4
Create Date: 2026-04-01 21:56:54.695291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723a96a8f359'
down_revision = '1164f30ee0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_shadowing_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_shadowing_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.FLOAT(), nullable=False),
    sa.Column('end_time', sa.FLOAT(), nullable=False),
    sa.Column('original_text', sa.TEXT(), nullable=True),
    sa.Column('accuracy_score', sa.INTEGER(), nullable=False),
    sa.Column('spoken_text', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('sentence_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], name=op.f('fk_shadowing_history_sentence_id_sentences')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
