"""migrating subtitles to content_json

Revision ID: 94137bf266a4
Revises: 67fa9ad740ba
Create Date: 2026-03-28 15:48:55.816843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94137bf266a4'
down_revision = '67fa9ad740ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###
