"""Added UI settings to Lesson and updated_at to Note

Revision ID: afda5c4560cf
Revises: c1e1319d31a4
Create Date: 2026-03-28 14:21:18.500636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afda5c4560cf'
down_revision = 'c1e1319d31a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settings_json', sa.Text(), nullable=True))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('settings_json')
    # ### end Alembic commands ###
