"""Add progress columns to SubtitleTrack

Revision ID: bcd3096e81fe
Revises: fe0c870ae1e9
Create Date: 2026-04-28 11:18:03.550033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd3096e81fe'
down_revision = 'fe0c870ae1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_lines', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_column('total_lines')
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
