"""Added uploader tracking to SubtitleTrack

Revision ID: c1e1319d31a4
Revises: c1c906ab8880
Create Date: 2026-03-28 13:34:23.368579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e1319d31a4'
down_revision = 'c1c906ab8880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploader_name', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_subtitle_tracks_users_uploader_id', 'users', ['uploader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subtitle_tracks_users_uploader_id', type_='foreignkey')
        batch_op.drop_column('uploader_name')
        batch_op.drop_column('uploader_id')

    # ### end Alembic commands ###
