"""Add status to subtitle_tracks

Revision ID: cf63fbd13969
Revises: d9a869c6c652
Create Date: 2026-04-03 20:44:12.377024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf63fbd13969'
down_revision = 'd9a869c6c652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shadowing_history', schema=None) as batch_op:
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('shadowing_history', schema=None) as batch_op:
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('video_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
