"""Add Deep Analysis tables

Revision ID: f72a6393b6f0
Revises: cf63fbd13969
Create Date: 2026-04-03 22:04:32.082956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72a6393b6f0'
down_revision = 'cf63fbd13969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sentences', schema=None) as batch_op:
        batch_op.drop_column('analysis_note')

    # ### end Alembic commands ###
