"""Add name and is_original to SubtitleTrack

Revision ID: fe0c870ae1e9
Revises: 1e99aea500f2
Create Date: 2026-04-28 11:10:48.551634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0c870ae1e9'
down_revision = '1e99aea500f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_original', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subtitle_tracks', schema=None) as batch_op:
        batch_op.drop_column('is_original')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
